// THIS FILE IS AUTOMATICALLY GENERATED BY /scripts/generate_plugin_bridge.ts
// AND IS NOT MEANT FOR MANUAL EDITING

import * as api from "$lib/index.svelte";
import * as event from "$lib/event/index.svelte";
import * as plugin from "$lib/plugin/index.svelte";
import * as project from "$lib/project.svelte";
import * as icons from "$lib/ui/icons.svelte";
import * as camera from "$lib/ui/camera.svelte";
import * as math from "$lib/math/index.svelte";
import * as database from "$lib/data/database.svelte";
import * as attribute from "$lib/data/attribute/index.svelte";
import * as utils from "$lib/util/index.svelte";
import * as components from "$lib/components/index.svelte";
import * as system from "$lib/system.svelte";
import * as ui from "$lib/ui/index.svelte";
import * as userdata from "$lib/userdata/index.svelte";

export function attachPluginData() {
	(globalThis as any).__CLARA_API__ = {
		api,
		event,
		plugin,
		project,
		icons,
		camera,
		math,
		database,
		attribute,
		utils,
		components,
		system,
		ui,
		userdata,
	};
}

const isWindows = navigator.userAgent.includes("Windows");
const scheme = isWindows ? "http://plugin.localhost/" : "plugin://localhost/";

export let importMap = {
	"@clara/api/": `${scheme}virtual/`,
	"@clara/api/api": `${scheme}virtual/api.js`,
	"@clara/api/event": `${scheme}virtual/event.js`,
	"@clara/api/plugin": `${scheme}virtual/plugin.js`,
	"@clara/api/project": `${scheme}virtual/project.js`,
	"@clara/api/icons": `${scheme}virtual/icons.js`,
	"@clara/api/camera": `${scheme}virtual/camera.js`,
	"@clara/api/math": `${scheme}virtual/math.js`,
	"@clara/api/database": `${scheme}virtual/database.js`,
	"@clara/api/attribute": `${scheme}virtual/attribute.js`,
	"@clara/api/utils": `${scheme}virtual/utils.js`,
	"@clara/api/components": `${scheme}virtual/components.js`,
	"@clara/api/system": `${scheme}virtual/system.js`,
	"@clara/api/ui": `${scheme}virtual/ui.js`,
	"@clara/api/userdata": `${scheme}virtual/userdata.js`,
};
