// THIS FILE IS AUTOMATICALLY GENERATED BY /scripts/generate_plugin_bridge.ts
// AND IS NOT MEANT FOR MANUAL EDITING

import * as api from "./index.svelte";
import * as event from "./event/index.svelte";
import * as plugin from "./plugin/index.svelte";
import * as project from "./project.svelte";
import * as icons from "./ui/icons.svelte";
import * as camera from "./ui/camera.svelte";
import * as math from "./math/index.svelte";
import * as database from "./data/database.svelte";
import * as attribute from "./data/attribute/index.svelte";
import * as utils from "./util/index.svelte";
import * as components from "./components/index.svelte";
import * as system from "./system.svelte";
import * as ui from "./ui/index.svelte";
import * as usersettings from "./usersettings/index.svelte";
import * as random from "./random/index.svelte";

export function attachPluginData() {
	(globalThis as any).__CLARA_API__ = {
		api,
		event,
		plugin,
		project,
		icons,
		camera,
		math,
		database,
		attribute,
		utils,
		components,
		system,
		ui,
		usersettings,
		random,
	};
}

const isWindows = navigator.userAgent.includes("Windows");
const scheme = isWindows ? "http://plugin.localhost/" : "plugin://localhost/";

export let importMap = {
	"@clara/api/": `${scheme}virtual/`,
	"@clara/api/api": `${scheme}virtual/api.js`,
	"@clara/api/event": `${scheme}virtual/event.js`,
	"@clara/api/plugin": `${scheme}virtual/plugin.js`,
	"@clara/api/project": `${scheme}virtual/project.js`,
	"@clara/api/icons": `${scheme}virtual/icons.js`,
	"@clara/api/camera": `${scheme}virtual/camera.js`,
	"@clara/api/math": `${scheme}virtual/math.js`,
	"@clara/api/database": `${scheme}virtual/database.js`,
	"@clara/api/attribute": `${scheme}virtual/attribute.js`,
	"@clara/api/utils": `${scheme}virtual/utils.js`,
	"@clara/api/components": `${scheme}virtual/components.js`,
	"@clara/api/system": `${scheme}virtual/system.js`,
	"@clara/api/ui": `${scheme}virtual/ui.js`,
	"@clara/api/usersettings": `${scheme}virtual/usersettings.js`,
	"@clara/api/random": `${scheme}virtual/random.js`,
};
