import apiMetadata from "../packages/api/package.json";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, "..");

const genDir = path.join(projectRoot, "generated");
if (fs.existsSync(genDir)) fs.rmSync(genDir, { recursive: true, force: true });
fs.mkdirSync(genDir);

const entryPoints = apiMetadata.exports;
console.log(Object.keys(entryPoints));

const modules = await Promise.all(
	Object.entries(entryPoints).map(async ([moduleKey, paths]) => {
		const moduleName = moduleKey === "." ? "api" : moduleKey.replace("./", "");
		console.log(`Generating plugin API bridge for module "${moduleName}"`);

		try {
			const modulePath = /dist\/(.+)\.js$/.exec(paths.default)![1];
			const sourcePath = path.join(projectRoot, `packages/api/src/lib/${modulePath}.ts`);
			const code = fs.readFileSync(sourcePath, "utf-8");

			console.log(`\tSearching for exports...`);

			const directExportRegex = /export\s+(?:async\s+)?(?:const|let|var|function|class)\s+([a-zA-Z0-9_]+)/g;
			const keys = new Set<string>();
			let match;

			while ((match = directExportRegex.exec(code)) !== null) {
				console.log(`\t\tFound export "${match[1]}"`);
				if (!match[1]) throw new Error(`Could not detect export name: ${match[1]}`);
				keys.add(match[1]);
			}

			const blockExportRegex = /export\s+\{([^}]+)\}/g;
			while ((match = blockExportRegex.exec(code)) !== null) {
				const content = match[1];
				content.split(",").forEach(part => {
					const trimmed = part.trim();
					if (!trimmed) return;
					const parts = trimmed.split(/\s+as\s+/);
					const exportName = parts[parts.length - 1];
					console.log(`\t\tFound export "${exportName}"`);
					if (!exportName) throw new Error(`Could not detect export name: ${content}`);
					keys.add(exportName);
				});
			}

			if (keys.size === 0) {
				throw new Error(`Module has "${moduleName}" has no detected exports (${sourcePath})`);
			}

			const bridgeCode = `// THIS FILE IS AUTOMATICALLY GENERATED BY /scripts/generate_plugin_bridge.ts\n// AND IS NOT MEANT FOR MANUAL EDITING\n\nconst internal = globalThis.__CLARA_API__.${moduleName};\n${Array.from(
				keys,
			)
				.map(k => `export const ${k} = internal.${k};`)
				.join("\n")}`;

			fs.writeFileSync(`${genDir}/${moduleName}.js`, bridgeCode);
			console.log(`\tDone! Successfully generated plugin API bridge for @clara/api/${moduleName}`);
			return { name: moduleName, path: `./${modulePath}` };
		} catch (e) {
			console.error(`Failed to generate plugin API bridge for ${moduleName}:`, e);
		}
	}),
);

const imports = modules.map(({ name, path }) => `import * as ${name} from "${path}";\n`).join("");
const importMap =
	'\t"@clara/api/": `${scheme}virtual/`,\n' +
	modules.map(({ name }) => '\t"@clara/api/' + name + '": `${scheme}virtual/' + name + ".js`,\n").join("");
const defineGlobals =
	"\t(globalThis as any).__CLARA_API__ = {\n" + modules.map(({ name, path }) => `\t\t${name},\n`).join("") + "\t};";
const code = `// THIS FILE IS AUTOMATICALLY GENERATED BY /scripts/generate_plugin_bridge.ts
// AND IS NOT MEANT FOR MANUAL EDITING

${imports}
export function attachPluginData() {
${defineGlobals}
}

const isWindows = navigator.userAgent.includes("Windows");
const scheme = isWindows ? "http://plugin.localhost/" : "plugin://localhost/";

export let importMap = {
${importMap}};
`;
fs.writeFileSync(path.join(projectRoot, "packages/api/src/lib/plugin_loader.svelte.ts"), code);
